version: '3.4'
services:

  app:
    build: .
    volumes:
      - .:/workspace:cached
    network_mode: service:database
    depends_on:
      - database

  database:
    image: postgres:12.5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres